# Generated by Django 4.2.5 on 2023-09-09 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=200)),
                ('course_fee', models.IntegerField()),
                ('course_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(choices=[('Dipti Pawar', 'Dipti Pawar'), ('Ashwini Gite', 'Ashwini Gite'), ('Vrushali Varpe', 'Vrushali Varpe')], default='Online Platform', max_length=50)),
                ('full_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=13)),
                ('permanent_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('whatsapp_number', models.CharField(max_length=13)),
                ('alternate_number', models.CharField(max_length=13)),
                ('enquiry_message', models.TextField(blank=True, null=True)),
                ('how_did_you_hear_about_us', models.CharField(choices=[('Website', 'Website'), ('Social Media', 'Social Media'), ('Friends and Family', 'Friends and Family'), ('Staff', 'Staff'), ('Sulekha', 'Sulekha')], max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('technical_skills', models.CharField(max_length=200)),
                ('certifications_done', models.CharField(max_length=200)),
                ('area_of_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('training_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=50, null=True)),
                ('office_location_preference', models.CharField(blank=True, choices=[('Pune', 'Pune'), ('Nashik', 'Nashik')], max_length=10, null=True)),
                ('enquiry_Status', models.TextField(choices=[('Finalized', 'Finalized'), ('Pending', 'Pending'), ('Informed On whatsapp', 'Informed on whatsapp')], default='Pending', max_length=20)),
                ('seleted_course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enquiry_department.cource')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDiscusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_installments', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('QR Code', 'QR Code')], default='Cash', max_length=50)),
                ('first_installment', models.FloatField(default=0)),
                ('first_installment_date', models.DateField(default=datetime.datetime(2023, 9, 10, 16, 36, 5, 283961))),
                ('second_installment', models.FloatField(blank=True, null=True)),
                ('second_installment_date', models.DateField(blank=True, null=True)),
                ('third_installment', models.FloatField(blank=True, null=True)),
                ('third_installment_date', models.DateField(blank=True, null=True)),
                ('four_installment', models.FloatField(blank=True, null=True)),
                ('four_installment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('First Installment Done', 'First Installment Done'), ('Second Installment Done', 'Second Installment Done'), ('Third Installment Done', 'Third Installment Done'), ('Fouth Installment Done', 'Fouth Installment Done'), ('All Installments Completed', 'All Installments Completed')], default='Pending', max_length=100)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('final_amount', models.IntegerField(default=0)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry_department.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('follow_up_time', models.TimeField(blank=True, default=datetime.datetime(2023, 9, 9, 16, 36, 5, 283960))),
                ('remark', models.CharField(max_length=200)),
                ('followup_status', models.CharField(choices=[('Follow Up Done', 'Follow Up Done'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('enroll_flag', models.BooleanField(default=False)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry_department.enquiry')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enquiry_department.followupreason')),
            ],
        ),
    ]
