# Generated by Django 4.2.5 on 2023-09-09 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cource',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cource_name',
            new_name='Course_name',
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 9, 9, 17, 33, 36, 142505)),
        ),
        migrations.AlterField(
            model_name='paymentdiscusion',
            name='first_installment_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 17, 33, 36, 143502)),
        ),
    ]
