# Generated by Django 3.2.18 on 2023-09-14 05:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry_department', '0004_auto_20230914_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 9, 14, 11, 3, 33, 218493)),
        ),
        migrations.AlterField(
            model_name='paymentdiscusion',
            name='first_installment_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 11, 3, 33, 219491)),
        ),
    ]
